### ISSUE TITLE
Plugin error from feature-classifier: pop from empty list!

### ISSUE THREAD

**Issue by MalbertRogers** [yphsieh/16S-ITGDB#1]
Hello,

We have been wanting to give 16S-ITGDB a shot using QIIME2, but are unfortunately running into some issues. 
First off, your trained classifier is unfortunately not compatible with qiime2 versions from 2021. So, we decided to use the raw sequence and taxonomy files to train our own feature classifier. We followed all the steps required (according to https://docs.qiime2.org/2020.2/tutorials/feature-classifier/) and manage to generate a classifier file. However, for some reason it does not seem to work. If we try to run QIIME2 using this classifier we get the error message: 

```
Traceback (most recent call last):
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/q2cli/commands.py", line 339, in __call__
    results = action(**arguments)
  File "<decorator-gen-205>", line 2, in classify_sklearn
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/sdk/action.py", line 391, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_feature_classifier/classifier.py", line 215, in classify_sklearn
    reads = _autodetect_orientation(
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_feature_classifier/classifier.py", line 170, in _autodetect_orientation
    result = list(zip(*predict(first_n_reads, classifier, confidence=0.)))
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_feature_classifier/_skl.py", line 46, in predict
    for calculated in workers(jobs):
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_feature_classifier/_skl.py", line 54, in _predict_chunk
    return _predict_chunk_with_conf(pipeline, separator, confidence, chunk)
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_feature_classifier/_skl.py", line 81, in _predict_chunk_with_conf
    classes = [cls for cls in classes if cls[0].pop(0) == level]
  File "/opt/conda/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_feature_classifier/_skl.py", line 81, in <listcomp>
    classes = [cls for cls in classes if cls[0].pop(0) == level]
IndexError: pop from empty list

Plugin error from feature-classifier:

  pop from empty list
```

We have successfully obtained a trained classifier before using raw SILVA files, so it's unlikely that we are doing something wrong and so more likely that there might be something wrong/missing with your sequence and/or taxonomy files. 

Do you have any idea what might be going on and how it could be fixed?

**Comment by cil6758** [comment]
Hi, MalbertRogers:
      Sorry for the late reply. Thank you so much for raising this issue.
      It looks like the version of scikit-learn in QIIME2 2021 was not compatible with QIIME2 2020.8. Therefore, we retrained q2-classifiers for QIIME2 versions 2021 and 2022. The file names are "taxa_itgdb_q2_2022_11_clf.qza", "taxa_itgdb_q2_2021_08_clf.qza", and "taxa_itgdb_q2_2020_08_clf.qza". These classifiers are located in the "data" directory.  Please choose a version that is compatible with your QIIME2 pipeline. Hope this helps.

Best regards
